{
 "title": "zadanie1",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "employee", "query": { "query": "label_values(name)" } },
   { "name": "day", "query": { "query": "label_values(day)" } }
  ]
 },
 "panels": [
  {
   "title": "rozkład tygodiowy",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(employee{name=\"$employee\"}[$__interval])",
     "legendFormat": "{{day}}"
    }
   ]
  },
  {
   "title": "wykres tygodniowy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "last_over_time(employee{name=\"$employee\"}[$__interval])",
     "legendFormat": "{{day}}"
    }
   ]
  },
  {
   "title": "ile godzin % $employee wyrobił w $day",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((last_over_time(employee{day=\"$day\", name=\"$employee\"}[$__interval]))/8)*100",
     "legendFormat": "{{day}}"
    }
   ]
  },
  {
   "title": "czy $employee wyrobił 8h w $day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(employee{day=\"$day\",name=\"$employee\"}[$__interval])",
     "legendFormat": "hours"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}